version: "3.8"

services:
  db:
    image: mongo:3.6.18-xenial
    ports:
      - "27017:27017"
    restart: on-failure
  seed:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: seed.Dockerfile
    restart: on-failure
    environment:
      MONGO_CONNECTION_STR: "mongodb://db:27017"
  web:
    depends_on:
      - db
    build: ./
    restart: on-failure
    environment:
      MONGO_CONNECTION_STR: "mongodb://db:27017"
      PORT: 80
    # If you need to reach the application without any cache server, uncomment the following lines:
    ports:
      - "8080:80"
  varnish:
    depends_on:
      - web
    build: ./build/varnish
    ports:
      - "8081:80"
    restart: on-failure
  nuster:
    depends_on:
      - web
    build: ./build/nuster
    ports:
      - "8082:80"
    restart: on-failure
